name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Adjust this to your project's Go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: |
        echo "Running cache tests..."
        # Run all tests in the cache package with increased timeout for API tests
        go test -v -timeout 2m ./cache